# p:  page
# l:  line
# c:  cell
# t:  text
# i:  indent
# si: size
#   large: 大号字体
# st: style
#   book: 书名格式
#   book-half: 半书名格式
#   br: 小行换行

p = 312

[[l]]
t = "康熙字典"
si = "large"

[[l]]
t = "子集上"
si = "large"
i = 2

[[l]]
t = "一部"
si = "large"
i = 4

[[l]]
[[l.c]]
t = "一"
si = "large"

[[l.c]]
t = "古文"

[[l.c]]
t = "弌"
si = "large"

[[l.c]]
t = "唐韻"
st = "book"

[[l.c]]
t = "韻會"
st = "book"

[[l.c]]
t = "於悉切"

[[l.c]]
t = "集韻"
st = "book"

[[l.c]]
t = "正韻"
st = "book"

[[l.c]]
t = "益悉切𠀤漪入聲"

[[l.c]]
st = "br"

[[l.c]]
t = "說文"
st = "book"

[[l.c]]
t = "惟初大始道立於一造分天地化成萬物"

[[l]]
[[l.c]]
t = "廣韻"
st = "book"

[[l.c]]
t = "數之始也物之極也"

[[l.c]]
t = "易繫辭"
st = "book"

[[l.c]]
t = "天一地二"

[[l.c]]
t = "老子道德經"
st = "book"

[[l.c]]
t = "道生"

[[l.c]]
st = "br"

[[l.c]]
t = "一一生二 又"

[[l.c]]
t = "廣韻"
st = "book"

[[l.c]]
t = "同也"

[[l.c]]
t = "禮樂記"
st = "book"

[[l.c]]
t = "禮樂𠛬政其極一也"

[[l.c]]
t = "史記儒"
st = "book-half"

[[l]]
[[l.c]]
t = "林傳"
st = "book-half"

[[l.c]]
t = "韓生推詩之意而爲內外傳數萬言其語頗與齊魯閒殊"

[[l.c]]
st = "br"

[[l.c]]
t = "然其歸一也 又少也"

[[l.c]]
t = "顏延之庭誥文"
st = "book"

[[l.c]]
t = "選書務一不尚煩密"

[[l.c]]
t = "何"
st = "book-half"

[[l]]
[[l.c]]
t = "承天答顏永嘉書"
st = "book-half"

[[l.c]]
t = "竊願吾子舍兼而遵一也 又"

[[l.c]]
t = "增韻"
st = "book"

[[l.c]]
t = "純也"

[[l.c]]
t = "易"
st = "book-half"

[[l.c]]
st = "br"

[[l.c]]
t = "繫辭"
st = "book-half"

[[l.c]]
t = "天下之動貞夫一"

[[l.c]]
t = "老子道德經"
st = "book"

[[l.c]]
t = "天得一以淸地得一以寧"


[[l]]
[[l.c]]
t = "神得一以靈谷得一以盈萬物得一以生侯王得一以爲天下"

[[l.c]]
st = "br"

[[l.c]]
t = "唐書薛平傳"
st = "book"

[[l.c]]
t = "兵鎧完礪徭賦均一 又誠也"

[[l.c]]
t = "中庸"
st = "book"
